# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chargeTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.getPasswordBtn = QtWidgets.QPushButton(Form)
        self.getPasswordBtn.setObjectName("getPasswordBtn")
        self.gridLayout.addWidget(self.getPasswordBtn, 3, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.oriEditText = QtWidgets.QLineEdit(Form)
        self.oriEditText.setObjectName("oriEditText")
        self.gridLayout.addWidget(self.oriEditText, 1, 2, 1, 1)
        self.lockType_comboBox = QtWidgets.QComboBox(Form)
        self.lockType_comboBox.setObjectName("lockType_comboBox")
        self.lockType_comboBox.addItem("")
        self.lockType_comboBox.addItem("")
        self.gridLayout.addWidget(self.lockType_comboBox, 0, 1, 1, 1)
        self.invEditText = QtWidgets.QLineEdit(Form)
        self.invEditText.setObjectName("invEditText")
        self.gridLayout.addWidget(self.invEditText, 2, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.getPasswordBtn.setText(_translate("Form", "解密"))
        self.label_2.setText(_translate("Form", "密码："))
        self.label.setText(_translate("Form", "原钥："))
        self.lockType_comboBox.setItemText(0, _translate("Form", "md5"))
        self.lockType_comboBox.setItemText(1, _translate("Form", "caser"))
