# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mdHandle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(791, 610)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnZUp = QtWidgets.QPushButton(self.frame)
        self.btnZUp.setGeometry(QtCore.QRect(610, 210, 75, 23))
        self.btnZUp.setObjectName("btnZUp")
        self.btnZDown = QtWidgets.QPushButton(self.frame)
        self.btnZDown.setGeometry(QtCore.QRect(610, 300, 75, 23))
        self.btnZDown.setObjectName("btnZDown")
        self.btnXUp = QtWidgets.QPushButton(self.frame)
        self.btnXUp.setGeometry(QtCore.QRect(510, 260, 75, 23))
        self.btnXUp.setObjectName("btnXUp")
        self.btnXDown = QtWidgets.QPushButton(self.frame)
        self.btnXDown.setGeometry(QtCore.QRect(390, 260, 75, 23))
        self.btnXDown.setObjectName("btnXDown")
        self.btnYUp = QtWidgets.QPushButton(self.frame)
        self.btnYUp.setGeometry(QtCore.QRect(440, 230, 75, 23))
        self.btnYUp.setObjectName("btnYUp")
        self.btnYDown = QtWidgets.QPushButton(self.frame)
        self.btnYDown.setGeometry(QtCore.QRect(440, 290, 75, 23))
        self.btnYDown.setObjectName("btnYDown")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(390, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(530, 20, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnZUp.setText(_translate("Form", "Z+"))
        self.btnZDown.setText(_translate("Form", "Z-"))
        self.btnXUp.setText(_translate("Form", "X+"))
        self.btnXDown.setText(_translate("Form", "X-"))
        self.btnYUp.setText(_translate("Form", "Y+"))
        self.btnYDown.setText(_translate("Form", "Y-"))
        self.pushButton_7.setText(_translate("Form", "连接"))
